services:
  ### ✅ API Backend (Azure Functions in .NET 9) ###
  api:
    container_name: "api"
    build:
      context: ./src/api
      dockerfile: ServiceLayer.API/Dockerfile
    platform: linux/amd64
    restart: always
    environment:
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
      AzureWebJobsStorage: "${AZURE_WEB_JOBS_STORAGE}"
      AzureWebJobsSecretStorageType: "files"
    ports:
      - "${API_PORT}:80"
    networks:
      - backend


networks:
  backend:
    driver: bridge
