FROM mcr.microsoft.com/dotnet/sdk:9.0 AS installer-env
WORKDIR /src/dotnet-function-app

COPY ./dotnet-mesh-client/application/DotNetMeshClient/NHS.Mesh.Client/NHS.Mesh.Client.csproj ../dotnet-mesh-client/application/DotNetMeshClient/NHS.Mesh.Client/
COPY ./ServiceLayer.Shared/ServiceLayer.Shared.csproj ../ServiceLayer.Shared/
COPY ./ServiceLayer.Mesh/ServiceLayer.Mesh.csproj .
RUN dotnet restore

COPY ./dotnet-mesh-client/ ../dotnet-mesh-client/
COPY ./ServiceLayer.Common/ ../ServiceLayer.Common/
COPY ./ServiceLayer.Mesh/ .

RUN dotnet publish -c Release -o /home/site/wwwroot

FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated9.0 AS production
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
    ASPNETCORE_ENVIRONMENT=Production

RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser
USER appuser

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]
